### ISSUE TITLE
It doesn't work anymore on Big Sur beta 4

### ISSUE THREAD

**Issue by equinusocio** [Mafrans/StadiaPlus#101]
With the latest release of macOs Big Sur Beta 4 Stadia+ stopped working. This latest update introduced the VP9 support for Safari, which can now reproduce 4K videos on youtube, probably it's related.

After installing the extension the Stadia+ menus are missing from the UI (which has been updated).

**Comment by Mafrans** [comment]
This is due to an issue over on [StadiaGameDB](https://github.com/nilicule/StadiaGameDB) and will be fixed soon.
