### ISSUE TITLE
Possible problem with Hitman series

### ISSUE THREAD

**Issue by nilicule** [Mafrans/StadiaPlus#106]
Seems both Hitman and Hitman 2 have the same UUID:

Hitman 2:
https://stadia.google.com/u/2/store/details/990ec302c2cd4ba7817cedcf633ab20frcp1/sku/70d2750d0c614a01afbb34e5c4f3a9bc

Hitman:
https://stadia.google.com/u/2/store/details/990ec302c2cd4ba7817cedcf633ab20frcp1/sku/cc1997b89ae44886a1197a59b42b2613

I'm holding off pushing my changes for now, but how would you like to proceed?

**Comment by nilicule** [comment]
It seems the individual HITMAN games are grouped under a single game in Stadia, much like expansions.

Some more info on this here: https://www.ioi.dk/hitman-on-stadia/

I'll remove the HITMAN 2 entry from my list for now and group everything under the main game.

**Comment by Mafrans** [comment]
This may end up becoming an issue in the near future, will make sure to investigate possible fixes.

**Comment by nilicule** [comment]
Seems the only way around it is expanding the uuidmap with the sku, so my plan is to get the convertor implemented that'll convert the existing gamedb.json to the new format that we discussed a while ago.

Once that's in place you can parse the new format and we should be able to support both the old and the new DB.

**Comment by Mafrans** [comment]
Please notify me at least one week in advance of the new format and syntax so I can smoothly transfer

**Comment by Mafrans** [comment]
This seems to be solved as of 2.5
