### ISSUE TITLE
'Latency' stat should also include connection RTT

### ISSUE THREAD

**Issue by juberti** [Mafrans/StadiaPlus#11]
googCurrentDelayMs tracks several components of the audio playout latency, including algorithmic, jitter buffer, and sound card delay (see https://github.com/w3c/webrtc-stats/issues/151). However network delay is not included in this stat, so it needs to be added to get a more accurate value.

**Comment by Mafrans** [comment]
This may have been solved in [9fb57113e21af0c12ac835b91148d6200f3333d5](https://github.com/Mafrans/StadiaPlus/commit/9fb57113e21af0c12ac835b91148d6200f3333d5). Please confirm.
