### ISSUE TITLE
Play time is listed in hours instead of minutes

### ISSUE THREAD

**Issue by xcom923** [Mafrans/StadiaPlus#110]
When less than an hour of time is on a game the minutes are listed under hours in the overview. 

![image](https://user-images.githubusercontent.com/1283788/92458322-36cb4880-f193-11ea-92d0-5ed0017220b0.png)

The sorting is accurate so this is likely just a display issue. If I had to guess there needs to be a 0 set for hours when the minutes are less than 60. Also something I noticed is when there are no minutes there should be a "0m" instead of " m" Please look at the Orcs Must Die! 3 part of the screenshot for an example.

**Comment by Mafrans** [comment]
Working on this!

**Comment by Mafrans** [comment]
This is solved as of https://github.com/Mafrans/StadiaPlusDB/commit/854fd38e6616cea287587821b949b0f4c36e99d4
