### ISSUE TITLE
Missing game recordings and screenshots

### ISSUE THREAD

**Issue by TheBFGNL** [Mafrans/StadiaPlus#113]
Since today (well noticed it today) I'm missing my screenshots and recordings.

**Comment by Mafrans** [comment]
This is a noted bug. Until I make a fix, you can use https://stadia.google.com/captures to find your screenshots and recordings.

**Comment by Mafrans** [comment]
Fixed as of 2.5.3

**Comment by TheBFGNL** [comment]
Confirming that the fix is working 🥇
