### ISSUE TITLE
This is 2 problems but could be big could be small idk

### ISSUE THREAD

**Issue by arthurmelton** [Mafrans/StadiaPlus#116]
https://vimeo.com/461845247

**Comment by Mafrans** [comment]
I am looking into it, but it is possible that 2.5.2 has fixed it.

**Comment by arthurmelton** [comment]
one other bug and idk if others have had this but at first when you had the stadia+ DB page it recorded my first 2 games that I played and worked great but now it does not work and has not updated the 2 games or any game, Now with the auto-update still nothing. So I tried to delete my data that you had and now it has not updated any game even the 5 different games that I have played.

**Comment by Mafrans** [comment]
Leave that as a separate issue on https://github.com/Mafrans/StadiaPlusDB

**Comment by Mafrans** [comment]
Fixed as of 2.5.2
