### ISSUE TITLE
When in the store you dont see the captures button

### ISSUE THREAD

**Issue by arthurmelton** [Mafrans/StadiaPlus#119]
![image](https://user-images.githubusercontent.com/29708070/95390587-a08a5f80-08c3-11eb-91a1-5678963cedac.png)
![image](https://user-images.githubusercontent.com/29708070/95390617-ad0eb800-08c3-11eb-880c-2a90fe67feda.png)

**Comment by Mafrans** [comment]
Will work on that

**Comment by Mafrans** [comment]
Fixed as of 2.5.5
