### ISSUE TITLE
game filter not working

### ISSUE THREAD

**Issue by deekue** [Mafrans/StadiaPlus#12]
I see this error in the console when I load stadia.google.com

> Error handling response: TypeError: Cannot read property 'classList' of null
    at updateGame (chrome-extension://bbhmnnecicphphjamhdefpagipoegijd/injectors/filterInjector.js:81:12)
    at chrome-extension://bbhmnnecicphphjamhdefpagipoegijd/injectors/filterInjector.js:64:13

if I go to stadia.google.com/store I get ~20 of these errors

> filterInjector.js:130 Uncaught TypeError: Cannot read property 'visible' of undefined
    at filterInjector.js:130
    at NodeList.forEach (<anonymous>)
    at createImages (filterInjector.js:113)

Stadia+ Extension Version 1.2.1
Chromium (w/VA-API patches) Version 81.0.4000.3 (Developer Build)

**Comment by deekue** [comment]
of course, I reload while testing something else and now it works.  still getting the same errors though

**Comment by dasganni** [comment]
Same errors here and the ingame overlay is not visible. The Library Filtering is working.

**Comment by dasganni** [comment]
Well.. After seeing the new clock in the Shift-Tab Menu, I finally found the button for toggling on the filter as well as a button for forcing VP9. Good work though! I recommend adding these functions and a description here and in the Addon Description :)
