### ISSUE TITLE
One more bug and it is a fullscreen game list thing

### ISSUE THREAD

**Issue by arthurmelton** [Mafrans/StadiaPlus#120]
![image](https://user-images.githubusercontent.com/29708070/95613437-f4678680-0a32-11eb-8614-a5a95521702d.png)

**Comment by Mafrans** [comment]
What is your screen size (in inches) and resolution (in width x height format)?

**Comment by arthurmelton** [comment]
it is 1920 by 1200 and its width is 20.4 inches by 12.75 inches. (more precise numbers are here https://www.displayspecifications.com/en/model/f3cb58)

**Comment by arthurmelton** [comment]
and at this point, I only get the fullscreen glitch thing ._.

**Comment by arthurmelton** [comment]
https://i.imgur.com/RNrXRyj.jpg this is how the page looks for me now (the bar is also a little taller than the list right at the bottom) the store looks good tho its just the home screen

**Comment by Mafrans** [comment]
This is fixed as of c586d40cd00f9e223c45d7ed9b980f0b7f3db858
