### ISSUE TITLE
Stadia+ DB not creating an account

### ISSUE THREAD

**Issue by arthurmelton** [Mafrans/StadiaPlus#123]
Stadia+ DB is not creating an account for me (I used to have one then I deleted it bc it would not update my games a long time ago so the page should be https://stadiaplus.dev/profile/AMTitan/0000/games but it has not created an account for me in like 1 month or so)

**Comment by Mafrans** [comment]
I'll take a look at this!

**Comment by CootjeNL** [comment]
I had exactly the same problem. Today I worked with @Mafrans to find a solution. And he did fix this! So I expect a new release with this fix soon.
