### ISSUE TITLE
sorry that I am killing you with bugs but here is one more ;P

### ISSUE THREAD

**Issue by arthurmelton** [Mafrans/StadiaPlus#126]
![image](https://user-images.githubusercontent.com/29708070/96628108-ceb66900-12df-11eb-8490-019f33f0f903.png)
the top and bottom of the images are messed up

**Comment by Mafrans** [comment]
When does this happen?

**Comment by arthurmelton** [comment]
this just happened randomly

**Comment by ELowry** [comment]
This has happened to me also. I solved it by doing a full reload (`Ctrl+F5`).

I believe it might be linked to a discrepancy in CSS styling between two versions of Stadia+, with the older version remaining cached even after the update.

Either way, I will try and report if it happens again.

**Comment by rodstrom** [comment]
This happened to me when I resized the window after the page has loaded, however, after a fresh reload the images look fine. This might be fixed by detecting a window resize and reload the images.

**Comment by ELowry** [comment]
@rodstrom This issue has been addressed in the pull request #149 by actually replacing the system used for animating these images. As a result, things should become more responsive and work well with window size changes in the next update.

**Comment by Mafrans** [comment]
Solved as of #149
