### ISSUE TITLE
Found a bug (I am so sorry)

### ISSUE THREAD

**Issue by arthurmelton** [Mafrans/StadiaPlus#127]
![image](https://user-images.githubusercontent.com/29708070/97340580-5b21d800-185a-11eb-9965-5ddaad012ff5.png)

look at the navbar (if you want to replicate it you need to just go to the store and at the store, it is hard to see so go anywhere and you can see it better)

**Comment by Mafrans** [comment]
First, I have to reiterate that reporting bugs does nothing but help me, and you do not need to feel guilty or sorry for me having more to do (I would have to fix the bugs either way, you're only helping). Second, I did some research on this issue and it seems to be a bug in Stadia, and not related to Stadia+.
