### ISSUE TITLE
ik 1 more enhancement

### ISSUE THREAD

**Issue by arthurmelton** [Mafrans/StadiaPlus#139]
but maybe use the stadia game icon things from https://stadiasource.com/games
like this https://stadiasource.com/images/box_art/jpg/sekiro-shadows-die-twice.jpg its just https://stadiasource.com/images/box_art/jpg/(name).jpg

**Comment by ELowry** [comment]
If I remember correctly, the covers Mafrans decided to use are specifically selected because they have no text/title on them, which makes sense when procedurally cropping an image.
