### ISSUE TITLE
Stadia survey cannot load 

### ISSUE THREAD

**Issue by siritinga** [Mafrans/StadiaPlus#14]
Hi!

I noticed that when this extension is enabled, the survey about game experience that appears after playing the game cannot be filled in, it disappears in a second.

When the extension is disabled, the survey stays on screen so I can answer.

**Comment by vrodriguezf** [comment]
Same here

**Comment by Mafrans** [comment]
This is an issue with the way Stadia+ handles it's injection. I am looking for a solution, but for now you will have to disable the extension if you wish to answer the surveys. I am sorry for the inconvenience.
