### ISSUE TITLE
Add ability to force language

### ISSUE THREAD

**Issue by zdzichu** [Mafrans/StadiaPlus#142]
Hi,

Recently my Stadia homepage and games switched to my language (Polish). This is horrible. Could you please investigate is there a possibility for Stadia+ to force games language to English?

**Comment by ELowry** [comment]
Simply add `?hl=en_us&gl=us` (or `&hl=en_us&gl=us` in the case that the URL already contains other parameters) at the end of the Stadia URL. This is a universal system across almost all Google services.

If you wish to have this be always active, there are a few ways to go about it:

1. Load the page with that bit added to the URL and save this as a PWA shortcut/bookmark.
2. Set up a user script that checks if the string is present in the URL and redirects the page if not.
-----
Another thing that you might want to do is change the default language that is set in your browser. The way to do this can vary depending on the browser, and it will not guarantee that a website respects your settings, b_ut it often helps. To do this I would suggest you google "change default language [name of browser]".

**Comment by zdzichu** [comment]
Thanks, adding parameters in URL worked for me.
