### ISSUE TITLE
background img

### ISSUE THREAD

**Issue by arthurmelton** [Mafrans/StadiaPlus#148]
set the class to have a background img its cool! 
"Z5U6eb" - home & profile & settings
"xPDr9b" or "bKmv6c" or "lEPylf" - store
"hxhAyf" or "OzUE7e" or "XY6ZL" or "fi8Jxd" - shift tab thing

**Comment by ELowry** [comment]
Hey there!
Would you mind giving a bit more context to those classes?

For example, as far as I can tell `.Z5U6eb` is simply used to manage the main "page section" styling. What relationship does that have with background images?

Thanks in advance =)

**Comment by arthurmelton** [comment]
when in the home, profile, or settings run this in console (for the others change the class and you will see what I mean):

https://pastebin.com/i8ANiYKk

**Comment by arthurmelton** [comment]
and sorry for me its 11am and I was doing chorse

**Comment by Mafrans** [comment]
I'm having a hard time understanding this

**Comment by ELowry** [comment]
OK, the pastebin above results in the following:
![image](https://user-images.githubusercontent.com/7792033/99881658-46e3b780-2c1b-11eb-8f48-9c85f7859068.png)

These classes represent the main elements that could be used to set an overall document background image/texture.

**Comment by arthurmelton** [comment]
> OK, the pastebin above results in the following:
> ![image](https://user-images.githubusercontent.com/7792033/99881658-46e3b780-2c1b-11eb-8f48-9c85f7859068.png)
> 
> These classes represent the main elements that could be used to set an overall document background image/texture.

yea I at least like it so I was saying it bc the background could be anything so I was saying it bc others might like it and say with the custom profile pic you could have this , and others could see there custom background pic!

**Comment by arthurmelton** [comment]
and I gtg for 2 days so if you got questions you got to wait 2 days or figure it out.
