### ISSUE TITLE
Ratings error

### ISSUE THREAD

**Issue by arthurmelton** [Mafrans/StadiaPlus#153]
so on https://stadia.google.com/store/details/5a0e892c933c4f56b4d87976cb655ecfrcp1/sku/bcdca49dcac843f98ddb10e06ba83ee9 it shows as 4.5 stars but it says it is 76/100 and that is 3.8 stars.

**Comment by Mafrans** [comment]
This by intention, due to the relative lack of games rated >80 or <20, the rating scale is not linear.
