### ISSUE TITLE
ui

### ISSUE THREAD

**Issue by arthurmelton** [Mafrans/StadiaPlus#156]
![image](https://user-images.githubusercontent.com/29708070/101180612-cc9f3400-3619-11eb-8fdc-72ff18e34e30.png)

**Comment by actuallyatiger** [comment]
I also have this issue, it's also causing the Stadia+, monitor, and windowed buttons to no longer be buttons and the start a party and live stream button can be clicked through them.

**Comment by Mafrans** [comment]
Working on this, will be fixed in the next update.
