### ISSUE TITLE
No way to view captures

### ISSUE THREAD

**Issue by RealRedcodi** [Mafrans/StadiaPlus#157]
Where there typically are it says this 
![image](https://user-images.githubusercontent.com/21988518/101366121-927c9f00-3872-11eb-8d47-b9b47f05311f.png) but there is no icon in the navbar? 
![image](https://user-images.githubusercontent.com/21988518/101366221-af18d700-3872-11eb-880d-659fd7b3f7b4.png)

**Comment by Mafrans** [comment]
This is being worked on for the next version.
