### ISSUE TITLE
Immortals Fenyx Rising Demo game name not showing correctly

### ISSUE THREAD

**Issue by RealRedcodi** [Mafrans/StadiaPlus#158]
![image](https://user-images.githubusercontent.com/21988518/101398679-75f55c80-389c-11eb-9758-953bf6e950d5.png)
![image](https://user-images.githubusercontent.com/21988518/101398694-7d1c6a80-389c-11eb-82e4-078451026485.png)

**Comment by ELowry** [comment]
I believe this is an issue with https://github.com/nilicule/StadiaGameDB since the Demo had the same ID as the game until recently (it now has its own)
If you could post this over there it would be great!

**Comment by RealRedcodi** [comment]
Ok, done
