### ISSUE TITLE
Can't use party chat

### ISSUE THREAD

**Issue by ChrisKingDavis** [Mafrans/StadiaPlus#18]
I get disconnected from party chat everytime I join it

**Comment by iddicted** [comment]
I can report the same issue. When switching to in-game chat (e.g. destiny 2) I get a message "mic connected" but when switching back to stadia'd party chat it shows a message that I got disconnected. There is no disconnect happening, but the party chat doesn't work.

**Comment by julianxhokaxhiu** [comment]
Is it possible to know which was the core issue behind this?

**Comment by Mafrans** [comment]
It is still not 100% known what the issue was, but I speculate that it was due to the RTCPeerConnection hook being refreshed every second, meaning voicechat got reset.

**Comment by julianxhokaxhiu** [comment]
So I guess incidentally fixing the continuous refresh issue, you perhaps fixed audio connection too. Well done then, and thanks for the great effort on this extension :)
