### ISSUE TITLE
Refreshing after exiting a game prevents giving feedback.

### ISSUE THREAD

**Issue by zebRAW** [Mafrans/StadiaPlus#22]
I love Stadia+ and would like to keep using it. However I think it is very important and valuable to be able to give feedback regarding session quality after a game. Currently this is not possible as the page refreshes right after exiting a game session.

After a quick look it looks like this is done by the forceRefresh script. Is this necessary for the 'home' page or is this only needed for the 'store' page, as the latest commit message suggests?

**Comment by Mafrans** [comment]
The forceRefresh script is an ugly and temporary solution to a problem caused by the bad loading in Stadia+ 1.4.2 and below. Version 2.0 will fix this issue.

**Comment by zebRAW** [comment]
Thanks for the quick and insightful reply.
