### ISSUE TITLE
Launch games from the library with controller

### ISSUE THREAD

**Issue by ChristoferKarlsson** [Mafrans/StadiaPlus#50]
For some reason, it is only possible to launch the latest played game with a controller. When you try to launch any other game in the library, it is not possible to activate the play button from the controller. You either need to 1) use the mouse or 2) first hit the tab key to make the button selected (after this you can use the controller to launch the game).

This is not an issue with Stadia+ but with the Stadia site itself, so launching a games from the library with the controller would be classed as a feature suggestion.

**Comment by Mafrans** [comment]
I will investigate this

**Comment by Phase10-5828** [comment]
Can somebody mark this issue closed, Google has fixed the issue themselves, finally!
