### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by LiamDawe** [Mafrans/StadiaPlus#58]
Hi, unless I'm being stupid, I don't see a changelog anywhere?

**Comment by Mafrans** [comment]
There is usually a changelog on the reddit posts referencing major updates. Alternatively you can check the commits.

**Comment by LiamDawe** [comment]
Not ideal, really a changelog should be kept with the project here.

**Comment by Mafrans** [comment]
I will attempt to do so in the future.
