### ISSUE TITLE
No Instructions on how to use

### ISSUE THREAD

**Issue by brombomb** [Mafrans/StadiaPlus#6]
Installed the app.  Don't see the clock or overlay.  No instructions on how to enable/disable features...

Got crazy input lag, was trying to inspect what was going on but was unable to figure anything out.

The menu should provide quick toggles, and/or show hot keys

Running on a Samsung Chromebook+

**Comment by Mafrans** [comment]
That sounds like something being terribly wrong. The extension is still quite unperformant and I'm not sure whether low power Chromebooks can handle it.

The clock and filter should be enabled by default.

**Comment by brombomb** [comment]
I see the clock now.  I had to re-read the entire Reddit thread to find that hitting Ctrl + M to get the profile data.

**Comment by Mafrans** [comment]
There's also a button in the network tab that toggles the monitor. I'll see if we can implement some more natural way to do it.
