### ISSUE TITLE
Allow refreshing the page with a single click from within Stadia+ next to the 'Apply' button

### ISSUE THREAD

**Issue by sagz** [Mafrans/StadiaPlus#61]
Allow refreshing the page with a single click  in Stadia+ next to the 'Apply' button. Right now, it's a multi-step process: 1. Apply. 2. Hold Esc. 3. Refresh
<img width="560" alt="Screen Shot 2020-05-01 at 6 12 26 PM copy" src="https://user-images.githubusercontent.com/964843/80851738-69a77380-8bd8-11ea-971e-6f15ce337870.png">

**Comment by tobias-franke** [comment]
You can also refresh the site by opening the Stadia menu (which is open anyway, if you change the settings) and pressing F5.

**Comment by Mafrans** [comment]
It is recommended to press f5 or Ctrl+R to reload the page.
