### ISSUE TITLE
Persist Monitor Overlay Show/Hide settings across Stadia game sessions/refreshes

### ISSUE THREAD

**Issue by sagz** [Mafrans/StadiaPlus#62]
If I leave it on with a 'persist' checkbox, it will then auto-enable in my next game. Will save lots of clicks as I try to debug the forced-4k issue.

**Comment by sagz** [comment]
<img width="577" alt="Screen Shot 2020-05-01 at 6 24 10 PM" src="https://user-images.githubusercontent.com/964843/80851854-fc481280-8bd8-11ea-8077-5e148b366017.png">

**Comment by Mafrans** [comment]
Will take a look at this, they should be stored across sessions but might have issues.
