### ISSUE TITLE
Monitor and stadia+ buttons can't be activated by controller

### ISSUE THREAD

**Issue by WhippingBoy01** [Mafrans/StadiaPlus#72]
Some times I'm not able to activate the monitor and Stadia+ button by the controller but only using the mouse

**Comment by Mafrans** [comment]
Controller support is a long term project and not worked on actively right now.

**Comment by Mafrans** [comment]
Due to maintenance issues, I have now officially decided to forego controller support. If you prefer an extension with controller support, you should try Stadia Enhanced.
