### ISSUE TITLE
[Feature Request] Show Prices in Search results

### ISSUE THREAD

**Issue by Phase10-5828** [Mafrans/StadiaPlus#74]
I don't know if it's easy to set it up to follow whenever a sale happens, but it would be nice for it to show when I search, say "Monopoly" a pro logo followed by $10.00 then | $20.00 ~~$39.99~~
*Above is Just an Example, prices are subject to change

**Comment by Mafrans** [comment]
This isn't possible unless StadiaGameDB starts monitoring price changes.
