### ISSUE TITLE
Arch Linux Chromium Renderer Error

### ISSUE THREAD

**Issue by JPyke3** [Mafrans/StadiaPlus#77]
Hi, First of all, thanks for the great extension, it is pretty cool. Unfortunately, Whenever I install or run stadia+ it will crash my Chromium upon launch

This is the output from terminal whenever I launch stadia:

```
[5883:5883:0514/193907.846800:ERROR:browser_switcher_service.cc(238)] XXX Init()
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open i915 (search paths /usr/lib/dri)
failed to load driver: i915
MESA-LOADER: failed to open kms_swrast (search paths /usr/lib/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /usr/lib/dri)
failed to load swrast driver
libva error: /usr/lib/dri/iHD_drv_video.so init failed
[5910:5910:0514/193907.889788:ERROR:vaapi_wrapper.cc(485)] vaInitialize failed: unknown libva error
[5910:5910:0514/193907.889807:ERROR:vaapi_wrapper.cc(1157)] Failed to create VaapiWrapper for va_profile: VAProfileJPEGBaseline
libva error: /usr/lib/dri/iHD_drv_video.so init failed
[5910:5910:0514/193907.890851:ERROR:vaapi_wrapper.cc(485)] vaInitialize failed: unknown libva error
[5910:5910:0514/193907.890868:ERROR:vaapi_wrapper.cc(1157)] Failed to create VaapiWrapper for va_profile: VAProfileVP8Version0_3
[1]    5883 segmentation fault (core dumped)  MESA_GLSL_CACHE_DISABLE=true chromium
```

It looks like it can't find some drivers, which is strange because it works just fine without Stadia+ installed. Just wanted to report it, just in case my output helps :)

**Comment by Mafrans** [comment]
I'm no linux user, so I have a hard time decoding this, hopefully someone else can give me some pointers on what might be causing this. Maybe it's the same thing causing the Adblock incompatibilities?

**Comment by bassforce86** [comment]
https://wiki.archlinux.org/index.php/Hardware_video_acceleration#VAAPI_init_failed

I've just tried this in Chromium Version 80.0.3987.149 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit) - It worked fine

I'm obviously debian, not Arch - but i suspect it's a driver / hardware issue. Check the table above, hopefully it'll guide you in the right direction

**Comment by JPyke3** [comment]
Thanks for the feedback @bassforce86. Whilst I would usually agree about the driver issue. The thing that confused me was Chromium didn't crash when I removed Stadia+. I have tried it in `Version 81.0.4044.138 (Official Build) Arch Linux (64-bit)` and now I am working no worries. Thought it was an interesting scenario as to my knowledge, extensions are sandboxed are they not? Keen to learn about this though. 

Perhaps the stars aligned and there was a specific bug on my system for that version. I thought perhaps it could help lead to some useful debug info though, in case anyone else bumped into this issue. Feel free to close if you feel it is necessary

**Comment by Mafrans** [comment]
Extensions are sandboxed, but in order to do things like monitor network data Stadia+ takes some liberties and runs several scripts outside of the sandbox. I doubt they were the root cause, but it is possible.

**Comment by bassforce86** [comment]
If one of those it to check for VP9 to display the protocol, then it's possibly the cause. Although this certainly shouldn't cause Chromium to die. I imagine there are checks in place for checking VP9 existence / availability ? Chromium might be falsly reporting it's available, then failing to connect to the VAAPI becuase the driver isn't available

**Comment by bassforce86** [comment]
@JPyke3 Quick question, are you using Nvidia drivers? if so could you try a few things please:
- remove Stadia+ (so chromium starts)
- Disable Hardware acceleration
- Install Stadia+ (and restart chromium if required)

If that yeilds no success:

paste the output from chrome://gpu (redact any info you'd like not to be included, the output is huge, mainly interested in top section initially: "Graphics Feature Status")

paste output of `vdpauinfo` from your terminal - again redact what you don't want to share!

**Comment by matteocrippa** [comment]
Give a try to `chromium-vaapi` via aur should be good, only one issue you need to compile it and it takes a lot.

**Comment by JPyke3** [comment]
Hi guys thanks for the feedback and help. As I said in https://github.com/Mafrans/StadiaPlus/issues/77#issuecomment-630977356. I got it all sorted in the end. I am not sure what quite was triggering it but it has something to do with the i915 Integrated intel drivers. I was using chromium-vaapi in order to run stadia. And my GPU does support vp9 as can be seen via `vainfo`:

```
 jacob@jacob-mbp  ~  vainfo
vainfo: VA-API version: 1.7 (libva 2.7.1)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
```

I am not sure what caused this issue but if anyone stumbles upon it, I guess just ensure you run a system update and things should sort themselves out.

Closing.
