### ISSUE TITLE
ESC unlocks mouse in windowed mode.

### ISSUE THREAD

**Issue by mikamyrseth** [Mafrans/StadiaPlus#83]
When in window mode, the ESC key unlocks the mouse, giving this message.

> Your mouse is currently not captured by the game. Please click anywhere on the screen to lock your mouse cursor.

This behavior is different from when Stadia is in fullscreen, where it is possible to use ESC for bringing up game menues etc. Is it possible to implement the fullscreen behavior in windowed?

**Comment by Mafrans** [comment]
This could be a good change, but I don't see how it would be properly doable. Maybe someone else has any ideas?
