### ISSUE TITLE
Setting for forcing lower fps or less 1080p cpu usage

### ISSUE THREAD

**Issue by Problematist** [Mafrans/StadiaPlus#84]
I doubt this is possible, but my old PC is struggling with lag and heavy delay at 1080p.
This also happens in 60 fps YouTube videos but can be solved by turning hardware acceleration off.
On YouTube it's possible to remove the 60fps from higher resolutions with extensions since they pretend to the site that the browser can't handle anything over 30 fps: https://greasyfork.org/de/scripts/23329-disable-youtube-60-fps-force-30-fps
But that's just switching files, and it's possible that Stadia is 60 fps no matter what.

With Stadia it doesn't matter if I turn hardware acceleration on or off. Off is actually worse due to my CPU usage being constantly over 80%

**Comment by Mafrans** [comment]
It could theoretically be possible to intercept every other frame to provide a 30 fps stream, but it would require a lot of work to do properly and might affect performance in other fields. This is ultimately something Stadia should support on their own, as they have more control over the individual factors.

**Comment by Mafrans** [comment]
Keeping this open in case someone has additional information
