### ISSUE TITLE
[Request] Other resolutions

### ISSUE THREAD

**Issue by nihaals** [Mafrans/StadiaPlus#87]
Thought this would be a clearer way to talk about adding support for all the resolutions available (720p?, 1080p, 1440p, 4K and any others) and track progress.

* 720p - Implemented since 52f6b4af2d0fc0aa810094f95aee793448488802
* 1080p - Implemented since 2.0
* 1440p - Implemented since c9c4964229b02e60532110523a14389f8f71c293
* 4k - Implemented since 2.0

(The ones "since 2.0" were actually available before that but that is the current major version)

**Comment by Mafrans** [comment]
This has been implemented as of c84db96bd0c19fa950d827aa3707fae6269223c0
