### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by nihaals** [Mafrans/StadiaPlus#88]
It might be helpful for people, especially people who are new to Chrome or even general browser extensions, to have a CONTRIBUTING.md file so users know how to build, install and add any possible extensions (like live reload/watch). Could also help more people test PRs.

A range of contributors should probably help on this in case some people have specific tools that helped them debug for example much more easily.

**Comment by Mafrans** [comment]
Will work on that

**Comment by Mafrans** [comment]
This has been solved as of 5645a6b
