### ISSUE TITLE
Check hardware acceleration is enabled

### ISSUE THREAD

**Issue by vrodriguezf** [Mafrans/StadiaPlus#9]
Hi, thank you for this extension!

Would it be possible to include in the network overlay a check that says whether Chrome is using hardware acceleration to decode the video or not? I wonder if my current Chromium installation in Linux is using it to decode VP9.

Best!

**Comment by TheHippo** [comment]
This seems to be not possible right now: https://github.com/Modernizr/Modernizr/wiki/Undetectables#general-undetectables
